config/routes.rb
Rails.application.routes.draw do
  root 'uploads#index'
  get 'upload/:id' => 'uploads#show', as: :upload
  get 'upload' => 'uploads#new', as: :new_upload
  post 'upload' => 'uploads#create', as: :uploads

end

app/models/contact.rb
require 'i18n'

class Contact < ActiveRecord::Base
  belongs_to :upload

  validates :upload_id, presence: true
  validates :first_name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :last_name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  before_validation :transliterate

  private
  def transliterate
    self.email = I18n.transliterate(self.email)
    self.first_name = I18n.transliterate(self.first_name)
    self.last_name = I18n.transliterate(self.last_name)
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessor :file
  has_many :contacts

  after_create :create_contacts

  private
    def create_contacts
      spreadsheet = open_spreadsheet(file)
      (2..spreadsheet.last_row).each do |i| # We don't care about the header
        row = spreadsheet.row(i)

        first_name = row[0]
        last_name = row[1]
        email = row[2]

        contact = self.contacts.new(first_name: first_name, last_name: last_name, email: email)
        unless contact.save
          # Add the errors to an array and display it
          errors.add(:base, contact.errors.messages.first)
        end
      end
    end
    
    def open_spreadsheet(file)
      case File.extname(file.original_filename)
      when ".xls" then Excel.new(self.file.path, nil: ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def index
    @uploads = Upload.includes(:contacts).all
  end

  def show
    @upload = Upload.find params[:id]
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new upload_params

    unless @upload.save
      render text: @upload.errors.first
    end
  end

  private
    def upload_params
      params.require(:upload).permit(:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/create.html.erb
<h1>Upload #<%= @upload.id %></h1>

<% @upload.contacts.each do |contact| %>
  <% if contact.persisted? %>
    <h3><%= contact.first_name + " " + contact.last_name %></h3>
    <p>contact ok</p>
  <% else %>
    <h3><%= contact.first_name + " " + contact.last_name %></h3>
    <p><%= contact.errors.messages.first %></p>
  <% end %>
<% end %>

<hr>

<p>Persisted contacts: <%= @upload.contacts.where('id is not null').size %></p>

app/views/uploads/index.html.erb
<% if flash[:notice].present? %>
  <%= content_tag :p, flash[:notice] %>

  <h2>Persisted contacts (<%= @uploads.last.contacts.size %>)</h2>
  <% @uploads.last.contacts.each do |contact| %>
    <p><%= contact.first_name.capitalize %> <%= contact.last_name.capitalize %></p>
  <% end %>
  
  <hr>
<% end %>

<h1>Uploads</h1>

<% @uploads.each do |upload| %>
  <p><%= link_to "Upload #{upload.id}", upload_path(id: upload.id) %></p>
<% end %>

<hr>
<p><%= link_to "New upload", new_upload_path %></p>

app/views/uploads/new.html.erb
<h1>Import Contacts</h1>

<%= form_for @upload, multipart: true do |f| %>
  <p><%= f.file_field :file, accept: 'application/xls' %></p>
  <%= submit_tag "Import Contacts" %>
<% end %>

app/views/uploads/show.html.erb
<h1>Upload #<%= @upload.id %></h1>

<h2>Persisted contacts (<%= @upload.contacts.size %>)</h2>

<%= @upload.contacts.each do |contact| %>
  <p><%= contact.first_name.capitalize + " " + contact.last_name.capitalize %></p>
<% end %>